.PHONY: clean All

All:
	@echo "----------Building project:[ SizeofOperator - Debug ]----------"
	@cd "Project1" && "$(MAKE)" -f  "SizeofOperator.mk"
clean:
	@echo "----------Cleaning project:[ SizeofOperator - Debug ]----------"
	@cd "Project1" && "$(MAKE)" -f  "SizeofOperator.mk" clean
