.PHONY: clean All

All:
	@echo "----------Building project:[ Section_Challenge - Debug ]----------"
	@cd "Section_Challenge" && "$(MAKE)" -f  "Section_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section_Challenge - Debug ]----------"
	@cd "Section_Challenge" && "$(MAKE)" -f  "Section_Challenge.mk" clean
